apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  clusterName: jlewi-dev/us-central1/kf-2020-0424-001
  labels:
    kf-name: jlewi-dev
    mesh_id: jlewi-dev_us-central1_kf-2020-0424-001
  name: kf-2020-0424-001
  namespace: jlewi-dev
spec:
  initialNodeCount: 2
  location: us-central1
  loggingService: logging.googleapis.com/kubernetes
  minMasterVersion: 1.14.10-gke.36
  monitoringService: monitoring.googleapis.com/kubernetes
  nodeConfig:
    machineType: n1-standard-8
    metadata:
      disable-legacy-endpoints: "true"
    serviceAccountRef:
      name: kf-2020-0424-001-vm
    workloadMetadataConfig:
      nodeMetadata: GKE_METADATA_SERVER
  workloadIdentityConfig:
    identityNamespace: jlewi-dev.svc.id.goog
