apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  labels:
    kf-name: jlewi-dev
  name: kf-2020-0424-001-user
  namespace: jlewi-dev
spec:
  displayName: kubeflow user service account
