# Name of kubeconfig contexts for various 
# TODO(jlewi): Add kpt setters?
mgmt-ctxt: gke_jlewi-dev_us-central1_jlewi-mgmt-0420
kf-ctxt: gke_jlewi-dev_us-central1_kf-bp-0420-002 # {"type":"string","x-kustomize":{"partialSetters":[{"name":"kf-ctxt","value":"jlewi-dev"}]}}
