# The purpose of this file is to store values in setters
# so its easy to get them using yq for use in Make.
# TODO(jlewi): File a feature request to have kpt list-setters return the value
project: kubeflow-ci # {"type":"string","x-kustomize":{"partialSetters":[{"name":"gcloud.core.project","value":"kubeflow-ci"}]}}
name: kf-ci-management # {"type":"string","x-kustomize":{"partialSetters":[{"name":"name","value":"kf-ci-management"}]}}
location: us-central1 # {"type":"string","x-kustomize":{"partialSetters":[{"name":"location","value":"us-central1"}]}}
