# This is a patch for the management cluster.
# It is used to define user specific values.
apiVersion: identity.cnrm.cloud.google.com/v1alpha2
kind: IdentityNamespace
metadata:
  name: default
---
# TODO(jlewi): Use a regional cluster? There should no longer be any cost savings to using zonal
apiVersion: container.cnrm.cloud.google.com/v1alpha2
kind: ContainerCluster
metadata:
  clusterName: "jlewi-dev/us-central1-f/jlewi-mgmt-0420" # {"type":"string","x-kustomize":{"partialSetters":[{"name":"gcloud.core.project","value":"jlewi-dev"},{"name":"cluster-name","value":"jlewi-mgmt-0420"},{"name":"gcloud.compute.zone","value":"us-central1-f"}]}}
  name: jlewi-mgmt-0420 # {"type":"string","x-kustomize":{"setter":{"name":"cluster-name","value":"jlewi-mgmt-0420"}}}
spec:
  # Use a regional cluster. Regional offer higher availability and the cluster management fee is the same.
  location: us-central1 # {"type":"string","x-kustomize":{"setter":{"name":"gcloud.compute.region","value":"us-central1"}}}
