apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jlewi-dev # {"type":"string","x-kustomize":{"setter":{"name":"gcloud.core.project","value":"jlewi-dev"}}}
resources:
- ../../manifests/gcp/v2/management/cluster
patchesStrategicMerge:
- cluster.yaml
