apiVersion: container.cnrm.cloud.google.com/v1alpha2
kind: ContainerNodePool
metadata:
  clusterName: "root-270714/us-central1-f/management-root" # {"type":"string","x-kustomize":{"partialSetters":[{"name":"gcloud.core.project","value":"root-270714"},{"name":"cluster-name","value":"management-root"},{"name":"gcloud.compute.zone","value":"us-central1-f"}]}}
  name: default-pool
  namespace: "root-270714" # {"type":"string","x-kustomize":{"setter":{"name":"gcloud.core.project","value":"root-270714"}}}
spec:
  autoscaling:
    minNodeCount: 1
    maxNodeCount: 3
  nodeConfig:
    diskSizeGb: 100
    diskType: pd-standard
    machineType: n1-standard-4
    preemptible: false
    oauthScopes:
    - https://www.googleapis.com/auth/devstorage.read_only
    - https://www.googleapis.com/auth/logging.write
    - https://www.googleapis.com/auth/monitoring
    - https://www.googleapis.com/auth/servicecontrol
    - https://www.googleapis.com/auth/service.management.readonly
    - https://www.googleapis.com/auth/trace.append
    metadata:
      disable-legacy-endpoints: "true"
  management:
    autoRepair: true
    autoUpgrade: true
  clusterRef:
    name: management-root