
apiVersion: identity.cnrm.cloud.google.com/v1alpha2
kind: IdentityNamespace
metadata:
  name: default
  namespace: "root-270714" # {"type":"string","x-kustomize":{"setter":{"name":"gcloud.core.project","value":"root-270714"}}}
spec: {}
---
apiVersion: container.cnrm.cloud.google.com/v1alpha2
kind: ContainerCluster
metadata:
  clusterName: "root-270714/us-central1-f/management-root" # {"type":"string","x-kustomize":{"partialSetters":[{"name":"gcloud.core.project","value":"root-270714"},{"name":"cluster-name","value":"prod"},{"name":"gcloud.compute.zone","value":"us-central1-f"}]}}
  name: management-root # {"type":"string","x-kustomize":{"setter":{"name":"cluster-name","value":"prod"}}}
  namespace: "root-270714" # {"type":"string","x-kustomize":{"setter":{"name":"gcloud.core.project","value":"root-270714"}}}
spec:
  location: us-central1-f # {"type":"string","x-kustomize":{"setter":{"name":"gcloud.compute.zone"}}}
  workloadIdentity:
    identityNamespace: default
  ipAllocationPolicy:
    useIpAliases: true
  releaseChannel:
    channel: RAPID
  clusterTelemetry:
    type: enabled