apiVersion: v1
data:
  appName: jl-stack-0409-204015
  hostname: jl-stack-0409-204015.endpoints.jlewi-dev.cloud.goog
  ipName: jl-stack-0409-204015-ip
  project: jlewi-dev
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: iap-ingress-config
