apiVersion: v1
kind: ServiceAccount
metadata:
  name: kf-admin
  annotations:
    iam.gke.io/gcp-service-account: kf-bp-0420-002-admin@jlewi-dev.iam.gserviceaccount.com # {"type":"string","x-kustomize":{"setBy":"kpt","partialSetters":[{"name":"name","value":"kf-bp-0420-002"},{"name":"gcloud.core.project","value":"jlewi-dev"}]}}
