apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  labels:
    kustomize.component: iap-ingress
  name: gke-certificate
  namespace: istio-system
spec:
  domains:
  - kf-2020-0423-002.endpoints.jlewi-dev.cloud.goog
