# Define the Google Service Account to be used with CNRM
# in the management cluster.
# Also define the workload identity binding.
#
# These resources should be created with AnthosCLI since we
# need to bootstrap the management cluster.
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: cnrm-system-jlewi-dev # {"type":"string","x-kustomize":{"partialSetters":[{"name":"managed_project","value":"jlewi-dev"}]}}
  namespace: "jlewi-dev" # {"type":"string","x-kustomize":{"setBy":"kpt","setter":{"name":"managed_project","value":"jlewi-dev"}}}
spec:
  displayName: Service account for CNRM

---

# TODO(jlewi): Switch to IAMPolicyMember once anthos CLI supports that.
apiVersion: iam.cnrm.cloud.google.com/v1alpha1
kind: IAMPolicy
metadata:
  name: cnrm-system-jlewi-dev-wi # {"type":"string","x-kustomize":{"partialSetters":[{"name":"managed_project","value":"jlewi-dev"}]}}
  namespace: "jlewi-dev" # {"type":"string","x-kustomize":{"setBy":"kpt","setter":{"name":"managed_project","value":"jlewi-dev"}}}
spec:
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1alpha1
    kind: IAMServiceAccount
    name: cnrm-system-jlewi-dev # {"type":"string","x-kustomize":{"partialSetters":[{"name":"managed_project","value":"jlewi-dev"}]}}
  bindings:
    - role: roles/iam.workloadIdentityUser
      # TODO(jlewi): Doesn't look like anthos CLI actually supports policy member yet.
      members:
      - serviceAccount:jlewi-dev.svc.id.goog[cnrm-system/cnrm-controller-manager-jlewi-dev] # {"type":"string","x-kustomize":{"setBy":"kpt","partialSetters":[{"name":"host_project","value":"jlewi-dev"}, {"name":"managed_project","value":"jlewi-dev"}]}}
---
# Make the GCP SA a project owner
# TODO(jlewi): AnthosCLI doesn't appear to support IAMPolicy Member yet so 
# as a work around you will need to use gcloud

apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: cnrm-system-jlewi-dev-owner # {"type":"string","x-kustomize":{"partialSetters":[{"name":"managed_project","value":"jlewi-dev"}]}}
  namespace: "jlewi-dev" # {"type":"string","x-kustomize":{"setBy":"kpt","setter":{"name":"managed_project","value":"jlewi-dev"}}}
spec:
  member: serviceAccount:cnrm-system-jlewi-dev@jlewi-dev.iam.gserviceaccount.com # {"type":"string","x-kustomize":{"partialSetters":[{"name":"managed_project","value":"jlewi-dev"}]}}
  role: roles/owner
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: projects/jlewi-dev # {"type":"string","x-kustomize":{"partialSetters":[{"name":"managed_project","value":"jlewi-dev"}]}}

