apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  labels:
    kf-name: jlewi-dev
  name: kf-2020-0423-003-admin-istio-wi
  namespace: jlewi-dev
spec:
  member: serviceAccount:jlewi-dev.svc.id.goog[istio-system/kf-admin]
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: kf-2020-0423-003-admin
  role: roles/iam.workloadIdentityUser
