apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: kf-kcc-0415-001-admin@jlewi-dev.iam.gserviceaccount.com
  labels:
    app: cloud-endpoints-controller
    app.kubernetes.io/component: cloud-endpoints
    app.kubernetes.io/instance: cloud-endpoints-v0.7.0
    app.kubernetes.io/managed-by: kfctl
    app.kubernetes.io/name: cloud-endpoints
    app.kubernetes.io/part-of: kubeflow
    app.kubernetes.io/version: v0.7.0
    kustomize.component: cloud-endpoints
  name: kf-admin
  namespace: kubeflow
