apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../vendor/manifests/istio/istio/base # {"type":"string","x-kustomize":{"setBy":"kpt","partialSetters":[{"name":"kustomize_manifests_path","value":"../../../vendor/manifests"}]}}
