apiVersion: configmanagement.gke.io/v1
kind: ConfigManagement
metadata:
  name: config-management
  annotations:
    gke.io/cluster: gke://root-270714/us-central1-f/management-root
spec:
  clusterName: "gke://root-270714/us-central1-f/management-root"
  git:
    syncRepo: "https://source.developers.google.com/p/root-270714/r/management-root"
    #secretType: cookiefile
    secretType: gcenode # aka workload identity
    policyDir: "/root"
  # Install and enable Config Connector
  configConnector:
    #enabled: true
    enabled: false
  sourceFormat: unstructured

---

apiVersion: iam.cnrm.cloud.google.com/v1alpha1
kind: IAMServiceAccount
metadata:
  name: anthos-config-management
  namespace: root-270714
spec:
  displayName: Service Account for Anthos Config Management
  projectRoles:
  - roles/source.reader # TODO: Grant read access only to the repo

---

apiVersion: iam.cnrm.cloud.google.com/v1alpha1
kind: IAMPolicy
metadata:
  name: anthos-config-management
  namespace: root-270714
spec:
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1alpha1
    kind: IAMServiceAccount
    name: anthos-config-management
  bindings:
    - role: roles/iam.workloadIdentityUser
      members:
      - serviceAccount:root-270714.svc.id.goog[config-management-system/importer]
