# cloudresourcemanager, used for creating projects
apiVersion: cnrm.cloud.google.com/v1alpha1
kind: CloudService
metadata:
  name: cloudresourcemanager.googleapis.com
  namespace: "root-270714" # {"type":"string","x-kustomize":{"setter":{"name":"gcloud.core.project","value":"root-270714"}}}
spec:
  service: cloudresourcemanager.googleapis.com
