# Name of kubeconfig contexts for various 
# TODO(jlewi): Add kpt setters?
mgmt-ctxt: jlewi-mgmt-0420-jlewi-dev # {"type":"string","x-kustomize":{"partialSetters":[{"name":"mgmt-ctxt","value":"jlewi-mgmt-0420-jlewi-dev"}]}}
project: jlewi-dev # {"type":"string","x-kustomize":{"partialSetters":[{"name":"gcloud.core.project","value":"jlewi-dev"}]}}
location: us-central1 # {"type":"string","x-kustomize":{"partialSetters":[{"name":"location","value":"us-central1"}]}}
name: kf-2020-0423-002 # {"type":"string","x-kustomize":{"partialSetters":[{"name":"name","value":"kf-2020-0423-002"}]}}
