apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    cnrm.cloud.google.com/version: 1.7.1
  creationTimestamp: null
  labels:
    cnrm.cloud.google.com/managed-by-kcc: "true"
    cnrm.cloud.google.com/system: "true"
    cnrm.cloud.google.com/tf2crd: "true"
  name: dnsmanagedzones.dns.cnrm.cloud.google.com
spec:
  group: dns.cnrm.cloud.google.com
  names:
    categories:
    - gcp
    kind: DNSManagedZone
    plural: dnsmanagedzones
    shortNames:
    - gcpdnsmanagedzone
    - gcpdnsmanagedzones
    singular: dnsmanagedzone
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'apiVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            description:
              type: string
            dnsName:
              description: The DNS name of this managed zone, for instance "example.com.".
              type: string
            dnssecConfig:
              description: DNSSEC configuration
              properties:
                defaultKeySpecs:
                  description: |-
                    Specifies parameters that will be used for generating initial DnsKeys
                    for this ManagedZone. If you provide a spec for keySigning or zoneSigning,
                    you must also provide one for the other.
                  items:
                    properties:
                      algorithm:
                        description: String mnemonic specifying the DNSSEC algorithm
                          of this key
                        type: string
                      keyLength:
                        description: Length of the keys in bits
                        type: integer
                      keyType:
                        description: |-
                          Specifies whether this is a key signing key (KSK) or a zone
                          signing key (ZSK). Key signing keys have the Secure Entry
                          Point flag set and, when active, will only be used to sign
                          resource record sets of type DNSKEY. Zone signing keys do
                          not have the Secure Entry Point flag set and will be used
                          to sign all other types of resource record sets.
                        type: string
                      kind:
                        description: Identifies what kind of resource this is
                        type: string
                    type: object
                  type: array
                kind:
                  description: Identifies what kind of resource this is
                  type: string
                nonExistence:
                  description: Specifies the mechanism used to provide authenticated
                    denial-of-existence responses.
                  type: string
                state:
                  description: Specifies whether DNSSEC is enabled, and what mode
                    it is in
                  type: string
              type: object
            forwardingConfig:
              description: |-
                The presence for this field indicates that outbound forwarding is enabled
                for this zone. The value of this field contains the set of destinations
                to forward to.
              properties:
                targetNameServers:
                  description: |-
                    List of target name servers to forward to. Cloud DNS will
                    select the best available name server if more than
                    one target is given.
                  items:
                    properties:
                      ipv4Address:
                        description: IPv4 address of a target name server.
                        type: string
                    required:
                    - ipv4Address
                    type: object
                  type: array
              required:
              - targetNameServers
              type: object
            peeringConfig:
              description: |-
                The presence of this field indicates that DNS Peering is enabled for this
                zone. The value of this field contains the network to peer with.
              properties:
                targetNetwork:
                  description: The network with which to peer.
                  properties:
                    networkRef:
                      oneOf:
                      - not:
                          required:
                          - external
                        required:
                        - name
                      - not:
                          anyOf:
                          - required:
                            - name
                          - required:
                            - namespace
                        required:
                        - external
                      properties:
                        external:
                          type: string
                        name:
                          description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names'
                          type: string
                        namespace:
                          description: 'Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/'
                          type: string
                      type: object
                  required:
                  - networkRef
                  type: object
              required:
              - targetNetwork
              type: object
            privateVisibilityConfig:
              description: |-
                For privately visible zones, the set of Virtual Private Cloud
                resources that the zone is visible from.
              properties:
                networks:
                  items:
                    properties:
                      networkRef:
                        oneOf:
                        - not:
                            required:
                            - external
                          required:
                          - name
                        - not:
                            anyOf:
                            - required:
                              - name
                            - required:
                              - namespace
                          required:
                          - external
                        properties:
                          external:
                            type: string
                          name:
                            description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names'
                            type: string
                          namespace:
                            description: 'Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/'
                            type: string
                        type: object
                    required:
                    - networkRef
                    type: object
                  type: array
              required:
              - networks
              type: object
            visibility:
              description: |-
                The zone's visibility: public zones are exposed to the Internet,
                while private zones are visible only to Virtual Private Cloud resources.
                Must be one of: 'public', 'private'.
              type: string
          required:
          - dnsName
          type: object
        status:
          properties:
            conditions:
              description: Conditions represents the latest available observation
                of the resource's current state.
              items:
                properties:
                  lastTransitionTime:
                    description: Last time the condition transitioned from one status
                      to another.
                    type: string
                  message:
                    description: Human-readable message indicating details about last
                      transition.
                    type: string
                  reason:
                    description: Unique, one-word, CamelCase reason for the condition's
                      last transition.
                    type: string
                  status:
                    description: Status is the status of the condition. Can be True,
                      False, Unknown.
                    type: string
                  type:
                    description: Type is the type of the condition.
                    type: string
                type: object
              type: array
            nameServers:
              description: |-
                Delegate your managed_zone to these virtual name servers;
                defined by the server
              items:
                type: string
              type: array
          type: object
      required:
      - spec
      type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
