apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    cnrm.cloud.google.com/version: 1.7.1
  creationTimestamp: null
  labels:
    cnrm.cloud.google.com/managed-by-kcc: "true"
    cnrm.cloud.google.com/system: "true"
    cnrm.cloud.google.com/tf2crd: "true"
  name: computeaddresses.compute.cnrm.cloud.google.com
spec:
  group: compute.cnrm.cloud.google.com
  names:
    categories:
    - gcp
    kind: ComputeAddress
    plural: computeaddresses
    shortNames:
    - gcpcomputeaddress
    - gcpcomputeaddresses
    singular: computeaddress
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'apiVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            address:
              description: |-
                The static external IP address represented by this resource. Only
                IPv4 is supported. An address may only be specified for INTERNAL
                address types. The IP address must be inside the specified subnetwork,
                if any.
              type: string
            addressType:
              description: |-
                The type of address to reserve, either INTERNAL or EXTERNAL.
                If unspecified, defaults to EXTERNAL.
              type: string
            description:
              description: An optional description of this resource.
              type: string
            ipVersion:
              description: |-
                The IP Version that will be used by this address. Valid options are
                'IPV4' or 'IPV6'. The default value is 'IPV4'.
              type: string
            location:
              description: 'Location represents the geographical location of the ComputeAddress.
                Specify a region name or "global" for global resources. Reference:
                GCP definition of regions/zones (https://cloud.google.com/compute/docs/regions-zones/)'
              type: string
            networkRef:
              oneOf:
              - not:
                  required:
                  - external
                required:
                - name
              - not:
                  anyOf:
                  - required:
                    - name
                  - required:
                    - namespace
                required:
                - external
              properties:
                external:
                  type: string
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names'
                  type: string
                namespace:
                  description: 'Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/'
                  type: string
              type: object
            networkTier:
              description: |-
                The networking tier used for configuring this address. This field can
                take the following values: PREMIUM or STANDARD. If this field is not
                specified, it is assumed to be PREMIUM.
              type: string
            prefixLength:
              description: |-
                The prefix length of the IP range. If not present, it means the
                address field is a single IP address.

                This field is not applicable to addresses with addressType=EXTERNAL.
              type: integer
            purpose:
              description: |-
                The purpose of this resource, which can be one of the following values:

                - GCE_ENDPOINT for addresses that are used by VM instances, alias IP ranges, internal load balancers, and similar resources.

                This should only be set when using an Internal address.
              type: string
            subnetworkRef:
              oneOf:
              - not:
                  required:
                  - external
                required:
                - name
              - not:
                  anyOf:
                  - required:
                    - name
                  - required:
                    - namespace
                required:
                - external
              properties:
                external:
                  type: string
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names'
                  type: string
                namespace:
                  description: 'Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/'
                  type: string
              type: object
          required:
          - location
          type: object
        status:
          properties:
            conditions:
              description: Conditions represents the latest available observation
                of the resource's current state.
              items:
                properties:
                  lastTransitionTime:
                    description: Last time the condition transitioned from one status
                      to another.
                    type: string
                  message:
                    description: Human-readable message indicating details about last
                      transition.
                    type: string
                  reason:
                    description: Unique, one-word, CamelCase reason for the condition's
                      last transition.
                    type: string
                  status:
                    description: Status is the status of the condition. Can be True,
                      False, Unknown.
                    type: string
                  type:
                    description: Type is the type of the condition.
                    type: string
                type: object
              type: array
            creationTimestamp:
              description: Creation timestamp in RFC3339 text format.
              type: string
            labelFingerprint:
              description: |-
                The fingerprint used for optimistic locking of this resource.  Used
                internally during updates.
              type: string
            selfLink:
              type: string
            users:
              description: The URLs of the resources that are using this address.
              items:
                type: string
              type: array
          type: object
      type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
