# This package defines the overlays of all GCP infra
# config
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namespace should match the project.
# This assumes we are running CNRM in namespace mode and namespaces match project names.
namespace: jlewi-dev # {"type":"string","x-kustomize":{"setBy":"kpt","partialSetters":[{"name":"gcloud.core.project","value":"jlewi-dev"}]}}
resources:
- ../manifests/gcp/v2/cnrm
- iam_policy.yaml
