apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: kf-kcc-0415-001-admin-wi
  namespace: jlewi-dev
spec:
  member: serviceAccount:jlewi-dev.svc.id.goog[kubeflow/kf-admin]
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: kf-kcc-0415-001-admin
  role: roles/iam.workloadIdentityUser
