apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  labels:
    kubeflow.org.name: jlewi-dev
  name: kf-2020-0423-001-admin
  namespace: jlewi-dev
spec:
  displayName: kubeflow admin service account
